name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: update
      run: sudo apt update
    - name: submodules
      run: git submodule update --init --recursive
    - name: Install apt dependencies
      run: sudo apt install libboost-dev libboost-system-dev libspandsp-dev gnutls-dev libsrtp2-dev cmake ccache
    - name: Build ilbc 
      run: |
            cd libilbc
            cmake . -DCMAKE_INSTALL_LIBDIR=/lib -DCMAKE_INSTALL_INCLUDEDIR=/usr/include; cmake --build .; sudo cmake --install .
            cd ..
    - name: Build project
      run: |
            cd src
            make
